# Generated by Django 4.0.5 on 2022-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_welcomes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Welcomes',
        ),
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='Default_val', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='Default_val', max_length=100),
        ),
    ]
